Repository tellor-io/telliot-core, pull requests merged in 2022-01, with the labels that each got.

#172 Eip1559 gas
  .gitignore
  src/telliot_core/contract/contract.py
  src/telliot_core/gas/legacy_gas.py
  tests/test_contract.py
Labels: enhancement

#192 Bug fix for no returned transaction when tx reverted
  src/telliot_core/contract/contract.py
Labels: bug

#195 Add polygon testnet endpoint to defaults
  src/telliot_core/model/endpoints.py
Labels: enhancement

#202 Add support for Polygon TellorFlex reporter
  src/telliot_core/apps/core.py
  src/telliot_core/cli/commands/query.py
  src/telliot_core/data/abi/polygon-token-abi.json
  src/telliot_core/data/contract_directory.json
  src/telliot_core/model/endpoints.py
  src/telliot_core/reporters/reporter_utils.py
  src/telliot_core/tellor/tellorflex/oracle.py
  src/telliot_core/tellor/tellorflex/token.py
  tests/test_reporter_utils.py
  tests/test_tellorflex_polygon.py
Labels: documentation, enhancement
